### ISSUE TITLE
package name `zips` ?

### ISSUE THREAD

**Issue by pome-ta** [HeavySnowJakarta/A-guide-to-a-Shell#13]
I am very happy that guidebook exists. Thank you.

[A guide for beginners - A guide to a-Shell](https://bianshen00009.gitbook.io/a-guide-to-a-shell/basic-tutorials/readme-1#get-more-packages)

```
$ pkg install zips
```

> Package zips not found

I can't find `zips`.Is there a mistake in writing `zip`?

Or is it `zips` as a "reference example"?

**Comment by HeavySnowJakarta** [comment]
My iPad is currently not here. As the repository presents it should be `zip`. Let me confirm that later.

**Comment by pome-ta** [comment]
> My iPad is currently not here. As the repository presents it should be `zip`. Let me confirm that later.

Thanks for reading.

It is not a pressing issue and I hope you will take another look at it when you have time.

**Comment by HeavySnowJakarta** [comment]
Yeah ur right
