### ISSUE TITLE
\d in "Define the prompt" section

### ISSUE THREAD

**Issue by speculaas** [HeavySnowJakarta/A-guide-to-a-Shell#15]
Dear Mr HeavySnowJakarta,

Thanks for the document!

As title, what does \d mean?

I want to echo the current datetime.

I tried echo \d and also typed and executed "\d" directly in a-shell. And both these doesn't work.

**Comment by HeavySnowJakarta** [comment]
when you add `\d` into the variable `PS1` the prompt will show the current datetime. for example, when you set `PS1` as `$`, the terminal will show:

```
$ # your commands are typed here
```

and when you add `\d` into it (`\d $` as example):

```
[the datetime] $ # your commands are typed here`
```

here it is.
