### ISSUE TITLE
Minor observation

### ISSUE THREAD

**Issue by kraig104** [HeavySnowJakarta/A-guide-to-a-Shell#2]
It may be a copy/paste issue but it looks to me like  the word "dictionary" is used in several places in the documentation when the word you want is "directory"

For example: https://bianshen00009.gitbook.io/a-guide-to-a-shell/basic-tutorials/configure-your-vim

**Comment by HeavySnowJakarta** [comment]
Well, quite a stupid mistake.

**Comment by HeavySnowJakarta** [comment]
There are also some grammar errors. I have to make the time to fix them.

**Comment by kraig104** [comment]
Haha, not really, these things happen. It looked to me like some global search/replace had happened. Better to catch it now before it propagates!!
Cheers,  Kraig


PS, I wanted to have a shell on my phone so I could quickly log into an HPC site in France and run a small script that checks and reports progress on a multi-day simulation I’m running. The HPC site only allows shared key access rather than explicit logins. a-shell-mini worked perfectly, set up some keys, did a small .bashrc with some aliases and…voila… a few keystrokes on my phone and I can see how my runs are doing. Thanks!
