### ISSUE TITLE
Is "export" permanent?

### ISSUE THREAD

**Issue by Calorion** [HeavySnowJakarta/A-guide-to-a-Shell#8]
[Configure the Shell: Define the prompt](https://bianshen00009.gitbook.io/a-guide-to-a-shell/basic-tutorials/configure-the-shell) discusses how to use the `export` command, but it doesn't say whether the changes are permanent, or whether they revert when a new terminal is opened. It also doesn't say how to revert your changes. There is no manpage or internal help for the `export` command. Could more information on this command be added to this section of the Book?

**Comment by HeavySnowJakarta** [comment]
As I remembered it should be added to `.bashrc`. Doing experiments is always a good way.

**Comment by HeavySnowJakarta** [comment]
As my experiment it's not permanent, just the same as normal Linux computers.

**Comment by HeavySnowJakarta** [comment]
> but it doesn't say whether the changes are permanent, or whether they revert when a new terminal is opened. It also doesn't say how to revert your changes.

Added a sentence now. For help about `PS1` and `export`, I suggest searching for the net to get them.
